apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-pass-ingress
  namespace: mlops
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: student.berrouyne.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: student-pass-svc
                port:
                  number: 80
